# 🔑 Secrets pour Streamlit Cloud
# Ne commitez JAMAIS ce fichier avec de vraies clés !

# Remplacez par votre vraie clé OpenAI
OPENAI_API_KEY = "sk-votre-cle-openai-ici"

# Optionnel pour les versions futures
ANTHROPIC_API_KEY = "sk-ant-votre-cle-anthropic"
QUICKNODE_URL = "https://your-endpoint.com"
